PRODUCER_COUNT=${1:-1}
PARTITION_COUNT=${2:-3}
CONSUMER_COUNT=${3:-1}
DELIVERY_MODE=${4:-AT_LEAST_ONCE}


if [ "$DELIVERY_MODE" = "AT_MOST_ONCE" ]; then
    MEMPHIS_IDEMPOTENCY='false'
    MEMPHIS_CONSUMER_ACK_POLICY='auto'
    MEMPHIS_MAX_ACK_TIME_MS='60000'
    MEMPHIS_MAX_MESSAGE_DELIVERIES='1' # 재전송 없음
elif [ "$DELIVERY_MODE" = "EXACTLY_ONCE" ]; then
    MEMPHIS_IDEMPOTENCY='true'
    MEMPHIS_CONSUMER_ACK_POLICY='explicit'
    MEMPHIS_MAX_ACK_TIME_MS='60000'
    MEMPHIS_MAX_MESSAGE_DELIVERIES='10'
else # At Least Once
    DELIVERY_MODE='AT_LEAST_ONCE'
    MEMPHIS_IDEMPOTENCY='false'
    MEMPHIS_CONSUMER_ACK_POLICY='explicit'
    MEMPHIS_MAX_ACK_TIME_MS='60000'
    MEMPHIS_MAX_MESSAGE_DELIVERIES='10'
fi


PARTITION_COUNT=${PARTITION_COUNT} \
DELIVERY_MODE=${DELIVERY_MODE} \
MEMPHIS_IDEMPOTENCY=${MEMPHIS_IDEMPOTENCY} \
MEMPHIS_CONSUMER_ACK_POLICY=${MEMPHIS_CONSUMER_ACK_POLICY} \
MEMPHIS_MAX_ACK_TIME_MS=${MEMPHIS_MAX_ACK_TIME_MS} \
MEMPHIS_MAX_MESSAGE_DELIVERIES=${MEMPHIS_MAX_MESSAGE_DELIVERIES} \
docker compose \
  --env-file ../.env \
  --env-file ./.env \
  down --volumes --remove-orphans
# docker volume rm memphis_memphis-postgres-data


PRODUCER_COUNT=${PRODUCER_COUNT} \
CONSUMER_COUNT=${CONSUMER_COUNT} \
PARTITION_COUNT=${PARTITION_COUNT} \
DELIVERY_MODE=${DELIVERY_MODE} \
MEMPHIS_IDEMPOTENCY=${MEMPHIS_IDEMPOTENCY} \
MEMPHIS_CONSUMER_ACK_POLICY=${MEMPHIS_CONSUMER_ACK_POLICY} \
MEMPHIS_MAX_ACK_TIME_MS=${MEMPHIS_MAX_ACK_TIME_MS} \
MEMPHIS_MAX_MESSAGE_DELIVERIES=${MEMPHIS_MAX_MESSAGE_DELIVERIES} \
docker compose \
  --env-file ../.env \
  --env-file ./.env \
  up -d \
  --build \
  --force-recreate \
  --scale producer=${PRODUCER_COUNT} \
  --scale consumer=${CONSUMER_COUNT}


echo "producer count: ${PRODUCER_COUNT}"
echo "partition count: ${PARTITION_COUNT}"
echo "consumer count: ${CONSUMER_COUNT}"
echo "delivery mode: ${DELIVERY_MODE}"
echo "$(date '+%Y-%m-%d %H:%M:%S') docker compose up done"
