services:
  grafana:
    image: grafana/grafana
    container_name: simon_grafana
    ports:
      - "24000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: simon_prometheus
    ports:
      - "24090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: simon_cadvisor
    ports:
      - 24808:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only'
      - '-disable_metrics=percpu,process,sched,tcp,udp,diskIO,disk'
      - '-store_container_labels=false'
